spring:
  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            add:
              type:
                headers: false

  application:
    name: review

  datasource:
    url: jdbc:mysql://ziply-mysql:3306/ziply_review?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}

kakao:
  api:
    key: ${KAKAO_API_KEY}
    geocoding-url: "https://dapi.kakao.com/v2/local/search/address.json"
    coord2region-url: "https://dapi.kakao.com/v2/local/geo/coord2regioncode.json"

azure:
  storage:
    connection-string: ${AZURE_STORAGE_CONNECTION_STRING}
    container-name: ${AZURE_STORAGE_CONTAINER_NAME:measurement-images}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
